---
- name: Check if participant file list has changed
  ansible.builtin.stat:
    path: "{{ csv_file }}"
  register: csv_file_stat
  delegate_to: localhost

- name: Get my tournament participant list from CSV file # noqa: no-handler
  community.general.files.read_csv:
    path: "{{ csv_file }}"
    delimiter: ","
    fieldnames: ["seed", "team_name", "registered_on", "participant1", "participant2", "participant3", "participant4", "participant5", "participant6"]
  register: csv_teams_results
  delegate_to: localhost

- name: Remove header from CSV file results # noqa: no-handler
  ansible.builtin.set_fact:
    csgo_teams: "{{ csv_teams_results.list | rejectattr('seed', 'equalto', 'Seed ') | list }}"

- name: Get my teams list from get5api # noqa: no-handler
  ansible.builtin.uri:
    url: "{{ get5api_url }}/teams/myteams"
    method: GET
    return_content: true
    status_code: [200, 404]
    headers:
      user-api: "{{ vault_get5api_key }}"
      Accept: application/json
  register: get5api_teams

- name: Check if teams exists in get5api_teams
  ansible.builtin.set_fact:
    get5api_team_exists: "{{ get5api_teams.status != 404 and get5api_teams.json.teams | selectattr('name', 'equalto', cs.team_name) | list }}"
  loop: "{{ csgo_teams }}"
  loop_control:
    loop_var: cs
  register: get5api_team_exists

- name: print out get5api_team_exists
  ansible.builtin.debug:
    msg: "{{ get5api_team_exists.results }}"

- name: Create teams in get5api if they don't exist
  ansible.builtin.uri:
    url: "{{ get5api_url }}/teams"
    method: POST
    return_content: true
    status_code: [200]
    headers:
      user-api: "{{ vault_get5api_key }}"
      Accept: application/json
      Content-Type: application/json
    body_format: json
    body: "{{ lookup('template', 'get5api_team.json.j2') }}"
  when: >
    (not get5api_team_exists.results[csgo_idx].ansible_facts.get5api_team_exists) and
    (get5api_team_exists.results[csgo_idx].cs.team_name == item.team_name)
  loop: "{{ csgo_teams | list }}"
  loop_control:
    index_var: csgo_idx
  register: get5api_team_create_response
