- name: Include Debian packages
  ansible.builtin.include_vars: debian.yml
  when: ansible_os_family == "Debian"

- name: Check if i386 is enabled
  ansible.builtin.shell: |
    set -o pipefail
    dpkg --print-foreign-architectures | grep i386
  args:
    executable: /bin/bash
  register: result_i386_check
  changed_when: result_i386_check.rc == 1
  failed_when: result_i386_check.rc > 1
  when: packaging_enable_i386

- name: Enable i386 architecture
  ansible.builtin.command: dpkg --add-architecture i386
  when: packaging_enable_i386 and result_i386_check.rc == 1

- name: Update all packages
  ansible.builtin.apt:
    force_apt_get: true

- name: Install LGSM Debian 11 or above dependencies
  ansible.builtin.apt:
    name: '{{ package }}'
    state: present
  loop: '{{ debian_packages }}'
  loop_control:
    loop_var: package
  when: ansible_distribution_major_version|int >= 11

- name: Create user to manage {{ csgo_user_name }}
  ansible.builtin.user:
    name: "{{ csgo_user_name }}"
    comment: Counter Strike Server User
    shell: /bin/bash
    groups: sudo
    append: true
    generate_ssh_key: true
    ssh_key_bits: 4096
    ssh_key_file: '.ssh/id_rsa'
    state: present
  become: true
