- name: Check if i386 is enabled
  ansible.builtin.shell: |
    set -o pipefail
    dpkg --print-foreign-architectures | grep i386
  args:
    executable: /bin/bash
  become: true
  register: result_i386_check
  changed_when: result_i386_check.rc == 1
  failed_when: result_i386_check.rc > 1
  when: packaging_enable_i386

- name: Enable i386 architecture
  ansible.builtin.command: dpkg --add-architecture i386
  become: true
  when: packaging_enable_i386 and result_i386_check.rc == 1

- name: Update all packages
  ansible.builtin.apt:
    force_apt_get: true

- name: Install LGSM Debian 11 or above dependencies
  ansible.builtin.apt:
    pkg: 
      - 'curl'
      - 'wget'
      - 'file'
      - 'tar'
      - 'bzip2'
      - 'gzip'
      - 'unzip'
      - 'bsdmainutils'
      - 'python3'
      - 'util-linux'
      - 'ca-certificates'
      - 'binutils'
      - 'bc'
      - 'jq'
      - 'tmux'
      - 'netcat-traditional'
      - 'lib32gcc-s1'
      - 'lib32stdc++6'
      - 'docker'
      - 'docker-compose'
      - 'rsync'
    state: present
  become: true
  when: ansible_distribution_major_version|int >= 11

- name: Create user to manage {{ csgo_user_name }}
  ansible.builtin.user:
    name: "{{ csgo_user_name }}"
    comment: Counter Strike Server User
    shell: /bin/bash
    groups: sudo
    append: true
    generate_ssh_key: true
    ssh_key_bits: 4096
    ssh_key_file: '.ssh/id_rsa'
    state: present
  become: true
