- include_vars: debian.yml
  when: ansible_os_family == "Debian"

- name: Check if i386 is enabled
  shell: dpkg --print-foreign-architectures | grep i386
  register: result_i386_check
  changed_when: result_i386_check.rc == 1
  failed_when: result_i386_check.rc > 1
  when: packaging_enable_i386

- name: Enable i386 architecture
  command: dpkg --add-architecture i386
  when: packaging_enable_i386 and result_i386_check.rc == 1

- name: Update all packages
  apt: force_apt_get=yes

- name: Install LGSM Debian 11 or above dependencies
  apt:
    name: '{{ item }}'
    state: latest
  with_items: '{{ debian_packages }}'
  when: ansible_distribution_major_version|int >= 11
  become: true

- name: Create user to manage {{ csgo_user_name }}
  ansible.builtin.user:
    name: csgouser
    comment: Counter Strike Server User
    shell: /bin/bash
    groups: sudo
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    state: present
  become: true

- name: Make sure rasmus can interact with other users
  user:
    name: rasmus
    groups: sudo,csgouser,{{ csgo_user_name }}
    append: yes
  become: true
