---
- name: Include Linux preperation tasks
  ansible.builtin.include_tasks: "{{ item }}"
  tags:
    - linux_configuration
    - linux_prep
  loop:
    - linux_configuration.yml
    - linux_dependencies.yml
