sourcemod_version: "1.11.0-git6917-linux"
mmsource_version: "1.11.0-git1148-linux"
steamworks_version: "1.2.3c"
get5_version: "v0.11.0"
get5ws_version: "V4.0.1"
sourcemod:
  name: "sourcemod"
  version: "{{ sourcemod_version }}"
  url: "https://sm.alliedmods.net/smdrop/1.11/sourcemod-{{ sourcemod_version }}.tar.gz"
mmsource:
  name: "mmsource"
  version: "{{ mmsource_version }}"
  url: "https://mms.alliedmods.net/mmsdrop/1.11/mmsource-{{ mmsource_version }}.tar.gz"
steamworks:
  name: "steamworks"
  version: "{{ steamworks_version }}"
  url: "https://github.com/KyleSanderson/SteamWorks/releases/download/{{ steamworks_version }}/package-lin.tgz"
get5:
  name: "get5"
  version: "{{ get5_version }}"
  url: "https://github.com/splewis/get5/releases/download/{{ get5_version }}/get5-{{ get5_version }}.tar.gz"
get5ws:
  name: "get5ws"
  version: "{{ get5ws_version }}"
  url: "https://github.com/PhlexPlexico/G5WS/releases/download/{{ get5ws_version }}/G5WS.zip"


# Steam API
steam_appid: 730
steam_base_uri: "https://api.steampowered.com/IGameServersService"
steam_get_account_list_url: "{{ steam_base_uri }}/GetAccountList/v1/?key={{ vault_g5api_steamapikey }}"
steam_post_create_account: "{{ steam_base_uri }}/CreateAccount/v1/?key={{ vault_g5api_steamapikey }}&appid={{ steam_appid }}"
steam_post_reset_token: "{{ steam_base_uri }}/ResetLoginToken/v1/?key={{ vault_g5api_steamapikey }}"
