packaging_enable_i386: true
sourcemod:
  name: "sourcemod"
  version: "1.11.0-git6917-linux"
  url: "https://sm.alliedmods.net/smdrop/1.11/sourcemod-{{ sourcemod.version }}.tar.gz"
mmsource:
  name: "mmsource"
  version: "1.11.0-git1148-linux"
  url: "https://mms.alliedmods.net/mmsdrop/1.11/mmsource-{{ version }}.tar.gz"
steamworks:
  name: "steamworks"
  version: "1.2.3c"
  url: "https://github.com/KyleSanderson/SteamWorks/releases/download/{{ version }}/package-lin.tgz"
get5:
  name: "get5"
  version: "v0.11.0"
  url: "https://github.com/splewis/get5/releases/download/{{ get5.version }}/get5-{{ get5.version }}.tar.gz"
