- name: Create docker-compose file for cs go servers
  template:
    src: templates/docker-compose-servers.yml.j2
    dest: {{ csgo_server_path }}/docker-compose-servers.yml
    owner: {{ csgo_user_name }}
    group: {{ csgo_user_name }}
  

- name: Tear down existing services
  docker_compose:
    project_src: {{ csgo_server_path }}
    files: docker-compose-servers.yml
    state: absent
  

- name: pull latest linuxgsm-docker image
  docker_image:
    name: raks321/linuxgsm-docker
    source: pull
    tag: latest
  

- name: Run CSGO servers
  docker_compose:
    project_src: {{ csgo_server_path }}
    files: docker-compose-servers.yml
    remove_orphans: yes
  

