- name: Copy docker-compose file
  copy:
    src: templates/docker-compose-initial.yml.j2
    dest: "{{ csgo_server_path }}/docker-compose-initial.yml"
    owner: "{{ csgo_user_name }}"
    group: "{{ csgo_user_name }}"
  become: true

- name: Tear down existing services
  docker_compose:
    project_src: "{{ csgo_server_path }}"
    files: docker-compose-initial.yml
    state: absent
  become: true

- name: Pull latest raks321/linuxgsm-docker image
  docker_image:
    name: raks321/linuxgsm-docker
    source: pull
  become: true

- name: Check if initial csgo server files need to be installed
  stat:
    path: "{{ csgo_server_path }}/log/script/csgoserver-steamcmd.log"
  register: csgo_initial_install
  
- name: Report if files are installed
  debug:
    msg: "CSGO Initial Server files have been installed"
  when: csgo_initial_install.stat.exists

- name: Install initial files
  docker_compose:
    project_src: "{{ csgo_server_path }}"
    files: docker-compose-initial.yml
  when: not csgo_initial_install.stat.exists
  become: true

- name: Wait until service has installed or updated (1h timeout with 60s intervals)
  wait_for:
    path: "{{ csgo_server_path }}/log/script/csgoserver-steamcmd.log"
    search_regex: "Success! App '740' already up to date. | Success! App '740' fully installed."
    delay: 30
    sleep: 60
    timeout: 3600
  when: not csgo_initial_install.stat.exists
  become: true

- name: Tear down existing services
  docker_compose:
    project_src: "{{ csgo_server_path }}"
    files: docker-compose-initial.yml
    state: absent
  when: not csgo_initial_install.stat.exists
  become: true