- name: Create docker-compose file for cs go servers
  template:
    src: templates/docker-compose-servers.yml.j2
    dest: "{{ csgo_server_path }}/docker-compose-servers.yml"
    owner: "{{ csgo_user_name }}"
    group: "{{ csgo_user_name }}"
  become: true

- name: Tear down existing services
  docker_compose:
    project_src: "{{ csgo_server_path }}"
    files: docker-compose-servers.yml
    state: absent
  become: true

- name: pull latest linuxgsm-docker image
  docker_image:
    name: raks321/linuxgsm-docker
    source: pull
    tag: latest
  become: true

- name: Copy over config-lgsm csgo config files with template
  template:
    src: templates/config-lgsm/csgoserver/csgoserver.cfg.j2
    dest: "{{ csgo_server_path }}/config-lgsm/csgoserver/csgoserver{{ '%02d' % item }}.cfg"
  loop: "{{ range(1,  tournament_server_count + 1) }}"
  become: true

- name: Copy over config-lgsm csgo common files with template
  template:
    src: templates/config-lgsm/csgoserver/common.cfg.j2
    dest: "{{ csgo_server_path }}/config-lgsm/csgoserver/common.cfg"
  become: true

- name: Copy over csgo server config files with template
  template:
    src: templates/serverfiles/csgo/cfg/csgoserver.cfg.j2
    dest: "{{ csgo_server_path }}/serverfiles/csgo/cfg/csgoserver{{ '%02d' % item }}.cfg"
    mode: 0755
  loop: "{{ range(1,  tournament_server_count + 1) }}"
  become: true

- name: Folder for downloaded files
  file:
    path: "{{ csgo_server_path }}/downloads"
    state: directory
    owner: "{{ csgo_user_name }}"
    group: "{{ csgo_user_name }}"
    mode: 0755
  become: true

- name: Download csgo addons
  get_url:
    url: "{{ item.url }}"
    dest: "{{ csgo_server_path }}/downloads/{{ item.name }}-{{ item.version }}.tar.gz"
    mode: 0755
  loop:
    - "{{ sourcemod }}"
    - "{{ mmsource }}"
    - "{{ steamworks }}"
    - "{{ get5 }}"
  become: true

- name: Extract csgo addons
  unarchive:
    src: "{{ csgo_server_path }}/downloads/{{ item.name }}-{{ item.version }}.tar.gz"
    dest: "{{ csgo_server_path }}/serverfiles/csgo/addons"
    remote_src: yes
    owner: "{{ csgo_user_name }}"
    group: "{{ csgo_user_name }}"
    mode: 0755
  loop:
    - "{{ sourcemod }}"
    - "{{ mmsource }}"
    - "{{ steamworks }}"
    - "{{ get5 }}"
  become: true

- name: Run CSGO servers
  docker_compose:
    project_src: "{{ csgo_server_path }}"
    files: docker-compose-servers.yml
    remove_orphans: yes
  become: true
