- name: Create docker-compose file for cs go servers
  template:
    src: templates/docker-compose-servers.yml.j2
    dest: /home/csgoserver/server/docker-compose-servers.yml
    owner: csgoserver
    group: csgoserver
  become: true

- name: Tear down existing services
  docker_compose:
    project_src: /home/csgoserver/server
    files: docker-compose-servers.yml
    state: absent
  become: true

- name: pull latest linuxgsm-docker image
  docker_image:
    name: raks321/linuxgsm-docker
    source: pull
    tag: latest
  become: true

- name: Run CSGO servers
  docker_compose:
    project_src: /home/csgoserver/server
    files: docker-compose-servers.yml
    remove_orphans: yes
  become: true

