- name: Create docker-compose file for cs go servers
  ansible.builtin.template:
    src: templates/docker-compose/docker-compose-servers.yml.j2
    dest: "{{ csgo_server_path }}/docker-compose-servers.yml"
    owner: "{{ csgo_user_name }}"
    group: "{{ csgo_user_name }}"
    mode: 0644
  become: true

- name: Tear down existing services
  community.docker.docker_compose:
    project_src: "{{ csgo_server_path }}"
    files: docker-compose-servers.yml
    state: absent
  become: true

- name: Pull latest linuxgsm-docker image
  community.docker.docker_image:
    name: raks321/linuxgsm-docker
    source: pull
    tag: latest
  become: true

- name: Copy over config-lgsm csgo config files with template
  ansible.builtin.template:
    src: templates/config-lgsm/csgoserver/csgoserver.cfg.j2
    dest: "{{ csgo_server_path }}/config-lgsm/csgoserver/csgoserver{{ '%02d' % item }}.cfg"
    mode: 0755
  loop: "{{ range(1, tournament_server_count + 1) }}"
  become: true

- name: Copy over config-lgsm csgo common files with template
  ansible.builtin.template:
    src: templates/config-lgsm/csgoserver/common.cfg.j2
    dest: "{{ csgo_server_path }}/config-lgsm/csgoserver/common.cfg"
    mode: 0755
  become: true

- name: Copy over csgo server config files with template
  ansible.builtin.template:
    src: templates/serverfiles/csgo/cfg/csgoserver.cfg.j2
    dest: "{{ csgo_server_path }}/serverfiles/csgo/cfg/csgoserver{{ '%02d' % item }}.cfg"
    mode: 0755
  loop: "{{ range(1, tournament_server_count + 1) }}"
  become: true

- name: Copy over csgo admins_simple.ini config file with template
  ansible.builtin.template:
    src: "templates/serverfiles/csgo/addons/sourcemod/configs/admins_simple.ini.j2"
    dest: "{{ csgo_server_path }}/serverfiles/csgo/addons/sourcemod/configs/admins_simple.ini"
    owner: "{{ csgo_user_name }}"
    group: "{{ csgo_user_name }}"
    mode: 0755
  become: true

- name: Create bridged docker network named get5
  community.docker.docker_network:
    name: get5
    driver: bridge
  become: true

- name: Run CSGO servers
  community.docker.docker_compose:
    project_src: "{{ csgo_server_path }}"
    files: docker-compose-servers.yml
  become: true
