- name: Create docker-compose file for cs go servers
  template:
    src: templates/docker-compose-servers.yml.j2
    dest: "{{ csgo_server_path }}/docker-compose-servers.yml"
    owner: "{{ csgo_user_name }}"
    group: "{{ csgo_user_name }}"
  become: true

- name: Tear down existing services
  docker_compose:
    project_src: "{{ csgo_server_path }}"
    files: docker-compose-servers.yml
    state: absent
  become: true

- name: pull latest linuxgsm-docker image
  docker_image:
    name: raks321/linuxgsm-docker
    source: pull
    tag: latest
  become: true


- name: Copy over config-lgsm csgo config files with template
  template:
    src: templates/config-lgsm/csgoserver/csgoserver.cfg.j2
    dest: "{{ csgo_server_path }}/config-lgsm/csgoserver/csgoserver{{ '%02d' % item }}.cfg"
  loop: "{{ range(1,  tournament_server_count + 1) }}"
  become: true

- name: Run CSGO servers
  docker_compose:
    project_src: "{{ csgo_server_path }}"
    files: docker-compose-servers.yml
    remove_orphans: yes
  become: true


