- name: Create partition
  parted:
    device: /dev/sdb # TODO: change to variable
    number: 1
    state: present
    fs_type: ext4
  become: true

- name: Get partition UUID
  command: blkid -s UUID -o value /dev/sdb1 # TODO: change to variable
  become: true
  register: csgo_part_info

- name: mount new volumes and create fstab entries
  ansible.posix.mount:
    path: "/home/csgoserver/server"
    src: UUID={{ csgo_part_info.stdout }}
    state: mounted
    fstype: ext4
    opts: defaults,nofail
  become: true