gslt_token_csgoserver01: "1XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
gslt_token_csgoserver02: "2XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
gslt_token_csgoserver03: "3XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
gslt_token_csgoserver04: "4XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
gslt_token_csgoserver05: "5XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
gslt_token_csgoserver06: "6XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
gslt_token_csgoserver07: "7XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
gslt_token_csgoserver08: "8XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"