debian_packages:
  - bc
  - binutils
  - bsdmainutils
  - bzip2
  - ca-certificates
  - cpio
  - curl
  - distro-info
  - file
  - gzip
  - hostname
  - jq
  - lib32gcc-s1
  - lib32stdc++6
  - libsdl2-2.0-0:i386
  - netcat
  - python3
  - tar
  - tmux
  - unzip
  - util-linux
  - wget
  - xz-utils
